### ISSUE TITLE
Warning: useLayoutEffect does nothing on the server

### ISSUE THREAD

**Issue by Kentakoong** [jimmycallin/react-hook-videojs#176]
Well. I've using the dependency and this shows up. It's on the hook itself, because I haven't used any useLayoutEffect.

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at /my-path/node_modules/react-hook-videojs/dist/react-hook-videojs.umd.js:18:46
    at /my-path/node_modules/react-hook-videojs/dist/react-hook-videojs.umd.js:61:40
    at VideoPlayer (webpack-internal:///./src/common/components/application/Media/VideoPlayer/VideoPlayer.tsx:13:24)
    at div
    at ChapterDetails (webpack-internal:///./src/common/components/application/Chapter/ChapterView/ChapterDetails.tsx:19:27)
    at section
    at Section (webpack-internal:///./src/common/layouts/Section/Section.tsx:8:20)
    at section
    at Section (webpack-internal:///./src/common/layouts/Section/Section.tsx:8:20)
    at DeleteProvider (webpack-internal:///./src/common/components/application/DeleteProvider/DeleteProvider.tsx:21:27)
    at div
    at div
    at Page (webpack-internal:///./src/common/layouts/Page/Page.tsx:20:17)
    at Chapter (webpack-internal:///./src/common/templates/Chapter/Chapter.tsx:23:20)
    at CareerPathChapter
    at ApolloProvider (/my-path/node_modules/@apollo/client/react/context/context.cjs:50:21)
    at MyApp (webpack-internal:///./src/pages/_app.tsx:43:18)
    at StyleRegistry (/my-path/node_modules/next/dist/styled-jsx/dist/index/index.js:671:34)
    at AppContainer (/my-path/node_modules/next/dist/server/render.js:280:29)
    at AppContainerWithIsomorphicFiberStructure (/my-path/node_modules/next/dist/server/render.js:309:57)
    at div
    at Body (/my-path/node_modules/next/dist/server/render.js:596:21)
```

**Comment by jmaestree** [comment]
Same here, I'm using it in a `Nextjs` project, in a page which is using SSR.
